//------------------------------------------------------------------------------
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
//     Author:Yubao Li
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using OpenAuth.Repository.Core;

namespace OpenAuth.App.Request
{
    /// <summary>
       ///
       /// </summary>

    public class AddOrUpdateExternalDataSourceReq
    {
        /// <summary>
       ///创建时间
       /// </summary>
       public DateTime Createtime { get; set; }

       /// <summary>
       ///创建用户名
       /// </summary>
       public string Createusername { get; set; }

       /// <summary>
       ///创建用户ID
       /// </summary>
       public string Createuserid { get; set; }

       /// <summary>
       ///更新用户ID
       /// </summary>
       public string Updateuserid { get; set; }

       /// <summary>
       ///更新用户名
       /// </summary>
       public string Updateusername { get; set; }

       /// <summary>
       ///是否测试成功
       /// </summary>
       public bool? Testsuccess { get; set; }

       /// <summary>
       ///最后测试时间
       /// </summary>
       public DateTime? Updatetime { get; set; }

       /// <summary>
       ///主键
       /// </summary>
       public string Id { get; set; }

       /// <summary>
       ///是否启用
       /// </summary>
       public bool Enabled { get; set; }

       /// <summary>
       ///连接字符串
       /// </summary>
       public string Connectionstring { get; set; }

       /// <summary>
       ///描述
       /// </summary>
       public string Description { get; set; }

       /// <summary>
       ///密码
       /// </summary>
       public string Password { get; set; }

       /// <summary>
       ///用户名
       /// </summary>
       public string Username { get; set; }

       /// <summary>
       ///端口
       /// </summary>
       public int? Port { get; set; }

       /// <summary>
       ///服务器地址
       /// </summary>
       public string Server { get; set; }

       /// <summary>
       ///数据库名称
       /// </summary>
       public string Databasename { get; set; }

       /// <summary>
       ///数据库类型
       /// </summary>
       public int Dbtype { get; set; }

       /// <summary>
       ///数据源名称
       /// </summary>
       public string Name { get; set; }

       
    }
}